version: '2'
services:
  web:
    restart: always
    build: .
    volumes:
      - /opt/contest_of_champions:/opt/contest_of_champions
    links:
      - db:mysql
    container_name: contest_api_web
    command: /usr/local/bin/gunicorn -w 2 -b :5000 application:app
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    container_name: contest_api_db
    environment:
      MYSQL_USER: coc-user
      MYSQL_PASSWORD: coc-pass
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: area
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
