version: '2'
services:
  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /opt/contest_of_champions:/opt/contest_of_champions
    links:
      - db:mysql
    container_name: contest_api_web
    environment:
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    container_name: contest_api_db
    environment:
        MYSQL_USER: coc-user
        MYSQL_PASSWORD: coc-pass
        MYSQL_ROOT_PASSWORD: root-pass
        MYSQL_DATABASE: area
